name = "SiriusB"
authors = ["Miles Lucas <mdlucas@hawaii.edu>"]

[deps]
ADI = "904a6c7d-4c1b-562f-9573-ab2e7e1c7946"
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
CCDReduction = "b790e538-3052-4cb9-9f1f-e05859a455f5"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
HCIToolbox = "b6cd55e5-4d02-4e12-b82c-005f67e784bf"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PSFModels = "9ba017d1-7760-46cd-84a3-1e79e9ae9ddc"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SAOImageDS9 = "dbce9b26-8eb4-4825-964b-d4940cf8daff"
SkyCoords = "fc659fc5-75a3-5475-a2ea-3da92c065361"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ADI = "0.6, 0.7"
CCDReduction = "0.2.0"
ProgressLogging = "0.1.4"
julia = "1.6"
